services:
  api:
    build:
      context: ./apps/api
    env_file: .env.example
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - elasticsearch
  web:
    build:
      context: ./apps/web
    environment:
      NEXT_PUBLIC_WEB_BASE_URL: https://sphere.dlssr.in
      NEXT_PUBLIC_API_BASE_URL: https://sphere.dlssr.in/v1
    ports:
      - "3001:3000"
    depends_on:
      - api
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: homesphere
      POSTGRES_PASSWORD: homesphere
      POSTGRES_DB: homesphere
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docs/database-schema.sql:/docker-entrypoint-initdb.d/001-schema.sql:ro
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    ports:
      - "9200:9200"
volumes:
  postgres_data:
